### ISSUE TITLE
put_session should check socket.connected?

### ISSUE THREAD

**Issue by shortly-portly** [pentacent/phoenix_live_session#3]
Hi 

Me again :-). I have the following piece of code:

```
def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :open, %{"id" => id}) do

    socket
    |> assign(:page_title, "Open Company")
    |> assign(:company, Companies.get_company!(id))

    PhoenixLiveSession.put_session(socket, "company_id", id)
  end
```

As you know when a live view is first started it gets called twice, first as a regular http request and secondly as a socket. I "think" live_view session only gets set up once the socket is connected. If my :open acton is the first action the liveview needs to handle as it gets called as part of the initial http request. Because this is before the socket has been opened the call to put_session fails with the following error:

`key :__live_session_id__ not found in: %{companies:.......`

I believe the solution is to wrap PhoenixLiveSession.put_session in an if socket.connected? == true. That way there won't be an attempt to access the __live_session_id__ key before it has been set up.

Does this makes sense or am I missing something.

BTW this is a fantastic library and exactly what I was looking for so thank you so much for writing it.

**Comment by johns10** [comment]
I implemented a test in a live_view instead of a live component, but I still get the same error.  I think I've missed something in my setup, or I'm doing something incompatible.

**Comment by wmnnd** [comment]
Hey there, it looks like you were missing the call to `maybe_subscribe/2` in your `mount/3` callback. Alternatively, you were using a newer version of LiveView and the latest release should fix the issue you had :smiley:
