### ISSUE TITLE
Deploy to Gigalixir

### ISSUE THREAD

**Issue by johns10** [pentacent/phoenix_live_session#5]
I've been working with this library in development, and now I'm trying to get it running in production (on Gigalixir).  I'm not having much luck.  Every time I try to update the session, I'm getting `key :__live_session_id__ not found in: <socket>`.  I'm trying to get better debug/repro information.

**Comment by johns10** [comment]
It's because of this:
```
key :connected? not found in: #Phoenix.LiveView.Socket
```
To which I say ... wat?

**Comment by johns10** [comment]
This is absolutely bananas.  I have no idea why it would be the case.  I just assumed this was a standard attribute that always got set during the socket lifecycle.

Here's how I "fixed" it:

```
    socket
    |> authorize(session)
    |> Map.put(:connected?, Phoenix.LiveView.connected?(socket))
```
The only thing I'm left with at this point is ... maybe node version discrepancy?  It's totally nuts I had to set this manually.  I don't understand.

**Comment by wmnnd** [comment]
Uhm, you’re absolutely right, `connected?` was recently removed from Phoeix.LiveView.Socket:

https://github.com/phoenixframework/phoenix_live_view/commit/4c9f46d566d4f2c2062b68a1425faba8245d2595#diff-dbe072dea09d3c01df875a8493bb630a0b596112af249cd42420ae07a45bc253
